# __init__

test __init__ and load_data_from_path

In [1]:
import src.keylogging_analysis as ka

ll_kldf = ka.KeyLoggingDataFrame()
ll_kldf.load_data_from_path("ll",  "./data/keys.csv", "./data/messages.csv")
ll_kldf.to_csv("ll_default.csv")

lh_kldf = ka.KeyLoggingDataFrame()
lh_kldf.load_data_from_path("lh", "./data/events_anonymized.csv", "./data/messages_anonymized.csv")
lh_kldf.to_csv("lh_default.csv")

Loaded 135440 events
Created KeyLoggingDataFrame of shape (135440, 12)

c:\Users\kobet\keylogging_analysis\src\keylogging_analysis.py:209: UserWarning: There are 30368 keys without a corresponding message. These will not be included in the final dataframe
  warnings.warn(f"There are {num_orphaned} keys without a corresponding message. These will not be included in the final dataframe")

Loaded 587768 events
Dropped 577087 events occurring in anonymized messages.
Dropped 0 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
Created KeyLoggingDataFrame of shape (587768, 23)

# load_default_data

In [2]:
import src.keylogging_analysis as ka

default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh", include_anonymized=True, include_nonsense=False)


default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll", include_anonymized=False)

Loaded 587768 events
Dropped 70611 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
KeyLoggingDataFrame of shape (587768, 24)

ValueError: include_anonymized can only be specified when system='lh'.

##add_iki()

In [1]:
# add iki using default parameters
import src.keylogging_analysis as ka
default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh")

default_lh.add_iki()
print(default_lh.columns)
print(default_lh[['content', "event_for_message_type", 'key_time', "iki"]].head(30))

default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_iki()
print(default_ll[['content', "event_for_message_type", 'key_time', "iki"]].head(30))

Loaded 587768 events
Dropped 577087 events occurring in anonymized messages.
Dropped 70611 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
KeyLoggingDataFrame of shape (587768, 24)
Index(['Unnamed: 0', 'key_id', 'content', 'event_for_message_type', 'key_time',
       'message_id', 'user_status', 'message_content', 'message_created_at',
       'session_id', 'PERSONA_ID', 'USER_ID', 'TASK_ID', 'application',
       'creationDate_conversation', 'targetLang', 'tutorLang', 'hasTasks',
       'CREATOR_ID', 'SCENARIO_ID', 'preCreated', 'simulated',
       'archivedForProcessing', 'username', 'iki'],
      dtype='object')
                                      content event_for_message_type  \
0                                       3,067                      5
1                                         NaN                      4
2                                       3,067                      5
3                                           B                      0
4                                          BO                      0
5                                         BON                      0
6                                        BONJ                      0
7                                       BONJO                      0
8                                      BONJOU                      0
9                                     BONJOU                       0
10                                     BONJOU                      0
11                                      BONJO                      0
12                                       BONJ                      0
13                                        BON                      0
14                                         BO                      0
15                                          B                      0
16                                        NaN                      0
17                                          b                      0
18                                         bo                      0
19                                        bou                      0
20                                       bouj                      0
21                                      boujo                      0
22                                     boujou                      0
23                                    boujour                      0
24                                        NaN                      4
25                                        NaN                      0
26                                    boujour                      1
27  Comment tu vas? Tu es tombé de très haut!                      2
28                                        NaN                      3
29                                      2,505                      5

                  key_time     iki
0  2018-09-21 07:13:54.270     NaN
1  2018-09-21 07:14:07.751     NaN
2  2018-09-21 07:14:08.134     NaN
3  2018-09-21 07:14:16.829     NaN
4  2018-09-21 07:14:17.254   425.0
5  2018-09-21 07:14:17.527   273.0
6  2018-09-21 07:14:17.885   358.0
7  2018-09-21 07:14:18.834   949.0
8  2018-09-21 07:14:19.242   408.0
9  2018-09-21 07:14:19.591   349.0
10 2018-09-21 07:14:20.220   629.0
11 2018-09-21 07:14:20.374   154.0
12 2018-09-21 07:14:20.555   181.0
13 2018-09-21 07:14:20.726   171.0
14 2018-09-21 07:14:20.896   170.0
15 2018-09-21 07:14:21.090   194.0
16 2018-09-21 07:14:21.287   197.0
17 2018-09-21 07:14:22.663  1376.0
18 2018-09-21 07:14:22.994   331.0
19 2018-09-21 07:14:23.379   385.0
20 2018-09-21 07:14:23.705   326.0
21 2018-09-21 07:14:23.968   263.0
22 2018-09-21 07:14:24.204   236.0
23 2018-09-21 07:14:24.773   569.0
24 2018-09-21 07:14:26.444     NaN
25 2018-09-21 07:14:27.103  2330.0
26 2018-09-21 07:14:27.104     NaN
27 2018-09-21 07:14:27.104     NaN
28 2018-09-21 07:14:27.106     NaN
29 2018-09-21 07:14:27.575     NaN
Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
         content  event_for_message_type                key_time    iki
0              H                       0 2024-06-08 09:19:07.999    NaN
1             He                       0 2024-06-08 09:19:08.122  123.0
2            Hel                       0 2024-06-08 09:19:08.232  110.0
3           Hell                       0 2024-06-08 09:19:08.377  145.0
4          Hello                       0 2024-06-08 09:19:08.522  145.0
5              H                       0 2024-06-08 09:19:24.449    NaN
6             He                       0 2024-06-08 09:19:24.529   80.0
7            Hel                       0 2024-06-08 09:19:24.641  112.0
8           Hell                       0 2024-06-08 09:19:24.796  155.0
9          Hello                       0 2024-06-08 09:19:25.654  858.0
10           NaN                       5 2024-06-08 09:19:31.861    NaN
11             H                       0 2024-06-08 09:19:32.069    NaN
12            Ho                       0 2024-06-08 09:19:32.149   80.0
13           How                       0 2024-06-08 09:19:32.372  223.0
14          How                        0 2024-06-08 09:19:32.442   70.0
15         How a                       0 2024-06-08 09:19:32.620  178.0
16        How ar                       0 2024-06-08 09:19:32.772  152.0
17       How are                       0 2024-06-08 09:19:32.812   40.0
18      How are                        0 2024-06-08 09:19:32.950  138.0
19     How are y                       0 2024-06-08 09:19:33.015   65.0
20    How are yo                       0 2024-06-08 09:19:33.150  135.0
21   How are you                       0 2024-06-08 09:19:33.408  258.0
22  How are you?                       0 2024-06-08 09:19:33.596  188.0
23             H                       0 2024-06-08 12:43:49.194    NaN
24            Hi                       0 2024-06-08 12:43:49.275   81.0
25           Hi                        0 2024-06-08 12:43:49.461  186.0
26          Hi g                       0 2024-06-08 12:43:49.841  380.0
27         Hi gu                       0 2024-06-08 12:43:49.978  137.0
28        Hi guy                       0 2024-06-08 12:43:50.289  311.0
29       Hi guy!                       0 2024-06-08 12:43:50.379   90.0

In [2]:
# name parameter
# specify colname
import src.keylogging_analysis as ka
default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh")
default_lh.add_iki(colname="iki2")
print(default_lh.columns)

# use existing colname --> ValueError
default_lh = default_lh.add_iki(colname="iki2")

Loaded 587768 events
Dropped 577087 events occurring in anonymized messages.
Dropped 70611 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
KeyLoggingDataFrame of shape (587768, 24)
Index(['Unnamed: 0', 'key_id', 'content', 'event_for_message_type', 'key_time',
       'message_id', 'user_status', 'message_content', 'message_created_at',
       'session_id', 'PERSONA_ID', 'USER_ID', 'TASK_ID', 'application',
       'creationDate_conversation', 'targetLang', 'tutorLang', 'hasTasks',
       'CREATOR_ID', 'SCENARIO_ID', 'preCreated', 'simulated',
       'archivedForProcessing', 'username', 'iki2'],
      dtype='object')

ValueError: Column 'iki2' already exists in the DataFrame. Please choose a different name.

In [5]:
# use different settings for include_first_key and include_nontyping_events (LH)
# include_first_key=True, include_nontyping_events=False
import src.keylogging_analysis as ka
default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh")
default_lh.add_iki(colname="iki3", include_first_key=True, include_nontyping_events=False)
default_lh.add_iki(colname="iki4", include_first_key=True, include_nontyping_events=True)
print(default_lh[["content", "event_for_message_type", "iki3", "iki4"]].head())

# include_first_key=False, include_nontyping_events=True --> error
default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh")
default_lh.add_iki(colname="iki5", include_first_key=False, include_nontyping_events=True)

Loaded 587768 events
Dropped 577087 events occurring in anonymized messages.
Dropped 70611 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
KeyLoggingDataFrame of shape (587768, 24)
  content event_for_message_type    iki3     iki4
0   3,067                      5     NaN      NaN
1     NaN                      4     NaN  13481.0
2   3,067                      5     NaN    383.0
3       B                      0  8695.0   8695.0
4      BO                      0   425.0    425.0
Loaded 587768 events
Dropped 577087 events occurring in anonymized messages.
Dropped 70611 events occurring in messages which contain nonsense bursts
Dropped 0 events of native speakers
KeyLoggingDataFrame of shape (587768, 24)

ValueError: include_first_key can only be False if include_nontyping_events is False

In [6]:
# use different settings for include_first_key and include_nontyping_events (LL)
# include_first_key=True, include_nontyping_events=False
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_iki(colname="iki3", include_first_key=True, include_nontyping_events=False)
default_ll.add_iki(colname="iki4", include_first_key=True, include_nontyping_events=True)
print(default_ll[["content", "event_for_message_type", "iki3", "iki4"]].head())

# include_first_key=False, include_nontyping_events=True --> ValueError
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_iki(colname="iki5", include_first_key=False, include_nontyping_events=True)

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
  content  event_for_message_type   iki3   iki4
0       H                       0    NaN    NaN
1      He                       0  123.0  123.0
2     Hel                       0  110.0  110.0
3    Hell                       0  145.0  145.0
4   Hello                       0  145.0  145.0
Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)

ValueError: include_first_key can only be False if include_nontyping_events is False

## add_pause()

In [1]:
# add_pause without defineing method
import src.keylogging_analysis as ka

default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")

# add pause without defined method --> TypeError
default_ll.add_pause()

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)

TypeError: KeyLoggingDataFrame.add_pause() missing 1 required positional argument: 'method'

In [1]:
# add_pause with fixed threshold
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_pause(method="fixed", threshold=2000, colname="pause_fixed")
print(default_ll.columns)
print(default_ll[['content', "event_for_message_type", 'key_time', "pause_fixed"]].head(30))

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
1.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135438      135438  135439        1531                       NaN
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135438 2025-08-04 08:31:54.390                       5
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135438  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135438          96                               NaN
135439          96                               NaN

               message_created_at user_status    iki pause_fixed
0      2024-06-08 11:19:08.554499           L    NaN         NaN
1      2024-06-08 11:19:08.554499           L  123.0       False
2      2024-06-08 11:19:08.554499           L  110.0       False
3      2024-06-08 11:19:08.554499           L  145.0       False
4      2024-06-08 11:19:08.554499           L  145.0       False
...                           ...         ...    ...         ...
135435 2025-08-04 08:31:49.413733           L  127.0       False
135436 2025-08-04 08:31:49.413733           L  359.0       False
135437 2025-08-04 08:31:49.413733           L  221.0       False
135438 2025-08-04 08:31:56.936551           L    NaN         NaN
135439 2025-08-04 08:31:56.936551           L    NaN         NaN

[135440 rows x 15 columns]
Index(['Unnamed: 0', 'key_id', 'message_id', 'content', 'key_time',
       'event_for_message_type', 'message_uid', 'message_content', 'user_id',
       'session_id', 'reply_to_message_id', 'message_created_at',
       'user_status', 'pause_fixed'],
      dtype='object')
         content  event_for_message_type                key_time pause_fixed
0              H                       0 2024-06-08 09:19:07.999         NaN
1             He                       0 2024-06-08 09:19:08.122       False
2            Hel                       0 2024-06-08 09:19:08.232       False
3           Hell                       0 2024-06-08 09:19:08.377       False
4          Hello                       0 2024-06-08 09:19:08.522       False
5              H                       0 2024-06-08 09:19:24.449         NaN
6             He                       0 2024-06-08 09:19:24.529       False
7            Hel                       0 2024-06-08 09:19:24.641       False
8           Hell                       0 2024-06-08 09:19:24.796       False
9          Hello                       0 2024-06-08 09:19:25.654       False
10           NaN                       5 2024-06-08 09:19:31.861         NaN
11             H                       0 2024-06-08 09:19:32.069         NaN
12            Ho                       0 2024-06-08 09:19:32.149       False
13           How                       0 2024-06-08 09:19:32.372       False
14          How                        0 2024-06-08 09:19:32.442       False
15         How a                       0 2024-06-08 09:19:32.620       False
16        How ar                       0 2024-06-08 09:19:32.772       False
17       How are                       0 2024-06-08 09:19:32.812       False
18      How are                        0 2024-06-08 09:19:32.950       False
19     How are y                       0 2024-06-08 09:19:33.015       False
20    How are yo                       0 2024-06-08 09:19:33.150       False
21   How are you                       0 2024-06-08 09:19:33.408       False
22  How are you?                       0 2024-06-08 09:19:33.596       False
23             H                       0 2024-06-08 12:43:49.194         NaN
24            Hi                       0 2024-06-08 12:43:49.275       False
25           Hi                        0 2024-06-08 12:43:49.461       False
26          Hi g                       0 2024-06-08 12:43:49.841       False
27         Hi gu                       0 2024-06-08 12:43:49.978       False
28        Hi guy                       0 2024-06-08 12:43:50.289       False
29       Hi guy!                       0 2024-06-08 12:43:50.379       False

In [1]:
# try multiple pause methods
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_iki(colname="iki")
default_ll.add_pause(method="fixed", threshold=100, colname="pause100", iki_colname="iki")
default_ll.add_pause(method="fixed", threshold=200, colname="pause200", iki_colname="iki")
default_ll.add_pause(method="individualized", a=0, colname="pause_individualized1", iki_colname="iki")
default_ll.add_pause(method="individualized", a=1, colname="pause_individualized2", iki_colname="iki")

print(default_ll.loc[50:100, ['content', "iki", "pause100", "pause200", "pause_individualized1", "pause_individualized2"]])

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
1.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135438      135438  135439        1531                       NaN
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135438 2025-08-04 08:31:54.390                       5
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135438  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135438          96                               NaN
135439          96                               NaN

               message_created_at user_status    iki  pause100  pause200  \
0      2024-06-08 11:19:08.554499           L    NaN      <NA>      <NA>
1      2024-06-08 11:19:08.554499           L  123.0      True     False
2      2024-06-08 11:19:08.554499           L  110.0      True     False
3      2024-06-08 11:19:08.554499           L  145.0      True     False
4      2024-06-08 11:19:08.554499           L  145.0      True     False
...                           ...         ...    ...       ...       ...
135435 2025-08-04 08:31:49.413733           L  127.0      True     False
135436 2025-08-04 08:31:49.413733           L  359.0      True      True
135437 2025-08-04 08:31:49.413733           L  221.0      True      True
135438 2025-08-04 08:31:56.936551           L    NaN      <NA>      <NA>
135439 2025-08-04 08:31:56.936551           L    NaN      <NA>      <NA>

        median_iki  median_mad  individualized_threshold  \
0            119.0        43.0                       NaN
1            119.0        43.0                     119.0
2            119.0        43.0                     119.0
3            119.0        43.0                     119.0
4            119.0        43.0                     119.0
...            ...         ...                       ...
135435       146.0        40.0                     146.0
135436       146.0        40.0                     146.0
135437       146.0        40.0                     146.0
135438       133.5        55.5                       NaN
135439       133.5        55.5                       NaN

        pause_individualized1
0                        <NA>
1                        True
2                       False
3                        True
4                        True
...                       ...
135435                  False
135436                   True
135437                   True
135438                   <NA>
135439                   <NA>

[135440 rows x 20 columns]
1.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135438      135438  135439        1531                       NaN
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135438 2025-08-04 08:31:54.390                       5
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135438  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id  ...         message_created_at user_status    iki  \
0                1  ... 2024-06-08 11:19:08.554499           L    NaN
1                1  ... 2024-06-08 11:19:08.554499           L  123.0
2                1  ... 2024-06-08 11:19:08.554499           L  110.0
3                1  ... 2024-06-08 11:19:08.554499           L  145.0
4                1  ... 2024-06-08 11:19:08.554499           L  145.0
...            ...  ...                        ...         ...    ...
135435          96  ... 2025-08-04 08:31:49.413733           L  127.0
135436          96  ... 2025-08-04 08:31:49.413733           L  359.0
135437          96  ... 2025-08-04 08:31:49.413733           L  221.0
135438          96  ... 2025-08-04 08:31:56.936551           L    NaN
135439          96  ... 2025-08-04 08:31:56.936551           L    NaN

        pause100  pause200  pause_individualized1  median_iki  median_mad  \
0           <NA>      <NA>                   <NA>       119.0        43.0
1           True     False                   True       119.0        43.0
2           True     False                  False       119.0        43.0
3           True     False                   True       119.0        43.0
4           True     False                   True       119.0        43.0
...          ...       ...                    ...         ...         ...
135435      True     False                  False       146.0        40.0
135436      True      True                   True       146.0        40.0
135437      True      True                   True       146.0        40.0
135438      <NA>      <NA>                   <NA>       133.5        55.5
135439      <NA>      <NA>                   <NA>       133.5        55.5

        individualized_threshold  pause_individualized2
0                            NaN                   <NA>
1                          162.0                  False
2                          162.0                  False
3                          162.0                  False
4                          162.0                  False
...                          ...                    ...
135435                     186.0                  False
135436                     186.0                   True
135437                     186.0                   True
135438                       NaN                   <NA>
135439                       NaN                   <NA>

[135440 rows x 21 columns]
                             content    iki  pause100  pause200  \
50      Hi guy! Tell me when you're    29.0     False     False
51     Hi guy! Tell me when you're i  142.0      True     False
52    Hi guy! Tell me when you're in  270.0      True      True
53   Hi guy! Tell me when you're in!  480.0      True      True
54                                 H    NaN      <NA>      <NA>
55                                Hi  289.0      True      True
56                               Hi!   96.0     False     False
57                              Hi!   190.0      True     False
58                             Hi! I  178.0      True     False
59                            Hi! I'  101.0      True     False
60                           Hi! I'm   96.0     False     False
61                          Hi! I'm   128.0      True     False
62                         Hi! I'm t  142.0      True     False
63                        Hi! I'm th   61.0     False     False
64                       Hi! I'm the  129.0      True     False
65                      Hi! I'm ther  129.0      True     False
66                     Hi! I'm there   88.0     False     False
67                    Hi! I'm there!  132.0      True     False
68                               NaN    NaN      <NA>      <NA>
69                                 N    NaN      <NA>      <NA>
70                                Ni   46.0     False     False
71                               Nic  167.0      True     False
72                              Nice  354.0      True      True
73                             Nice,  145.0      True     False
74                            Nice,    83.0     False     False
75                           Nice, l  102.0      True     False
76                          Nice, le  143.0      True     False
77                         Nice, let  153.0      True     False
78                        Nice, let'  163.0      True     False
79                       Nice, let's   48.0     False     False
80                      Nice, let's    97.0     False     False
81                     Nice, let's s  156.0      True     False
82                    Nice, let's st  179.0      True     False
83                   Nice, let's sta  135.0      True     False
84                  Nice, let's star  141.0      True     False
85                 Nice, let's start  100.0     False     False
86                Nice, let's start!   86.0     False     False
87                               NaN    NaN      <NA>      <NA>
88                                 H    NaN      <NA>      <NA>
89                                Ho   58.0     False     False
90                               How   72.0     False     False
91                              How    83.0     False     False
92                             How a  172.0      True     False
93                            How ar  155.0      True     False
94                           How are   89.0     False     False
95                          How are   168.0      True     False
96                         How are y   69.0     False     False
97                        How are yo  178.0      True     False
98                       How are you  259.0      True      True
99                      How are you   106.0      True     False
100                    How are you ?  183.0      True     False

     pause_individualized1  pause_individualized2
50                   False                  False
51                    True                  False
52                    True                   True
53                    True                   True
54                    <NA>                   <NA>
55                    True                   True
56                   False                  False
57                    True                   True
58                    True                   True
59                   False                  False
60                   False                  False
61                   False                  False
62                    True                  False
63                   False                  False
64                   False                  False
65                   False                  False
66                   False                  False
67                    True                  False
68                    <NA>                   <NA>
69                    <NA>                   <NA>
70                   False                  False
71                    True                   True
72                    True                   True
73                    True                  False
74                   False                  False
75                   False                  False
76                    True                  False
77                    True                  False
78                    True                   True
79                   False                  False
80                   False                  False
81                    True                  False
82                    True                   True
83                    True                  False
84                    True                  False
85                   False                  False
86                   False                  False
87                    <NA>                   <NA>
88                    <NA>                   <NA>
89                   False                  False
90                   False                  False
91                   False                  False
92                    True                   True
93                    True                  False
94                   False                  False
95                    True                   True
96                   False                  False
97                    True                   True
98                    True                   True
99                   False                  False
100                   True                   True

In [ ]:
## add_pburst

In [1]:
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_pburst(colname="pburst",pause_method="fixed", pause_threshold=2000)
print(default_ll.columns)
print(default_ll[['content', "event_for_message_type", 'key_time', "pburst"]].head(30))

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)

KeyError: None

## add_action

In [2]:
## add_action
import src.keylogging_analysis as ka
import pandas as pd 
pd.set_option('display.max_rows', 300)

default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_action()
print(default_ll.columns)

print(default_ll[['content', "action"]].head(50))
print(default_ll[default_ll["message_id"] == 1449][['content', "action"]])

default_lh = ka.KeyLoggingDataFrame()
default_lh.load_default_data("lh")
default_lh.add_action()
print(default_lh.columns)
print(default_lh[['content', "action"]].head(300))

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
0.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135438      135438  135439        1531                       NaN
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135438 2025-08-04 08:31:54.390                       5
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135438  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135438          96                               NaN
135439          96                               NaN

               message_created_at user_status
0      2024-06-08 11:19:08.554499           L
1      2024-06-08 11:19:08.554499           L
2      2024-06-08 11:19:08.554499           L
3      2024-06-08 11:19:08.554499           L
4      2024-06-08 11:19:08.554499           L
...                           ...         ...
135435 2025-08-04 08:31:49.413733           L
135436 2025-08-04 08:31:49.413733           L
135437 2025-08-04 08:31:49.413733           L
135438 2025-08-04 08:31:56.936551           L
135439 2025-08-04 08:31:56.936551           L

[135440 rows x 13 columns]
1.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135434      135434  135435        1530     tu peux mieux écrire
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135434 2025-08-04 08:27:42.041                       0
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135434  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135434          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135439          96                               NaN

               message_created_at user_status
0      2024-06-08 11:19:08.554499           L
1      2024-06-08 11:19:08.554499           L
2      2024-06-08 11:19:08.554499           L
3      2024-06-08 11:19:08.554499           L
4      2024-06-08 11:19:08.554499           L
...                           ...         ...
135434 2025-08-04 08:31:49.413733           L
135435 2025-08-04 08:31:49.413733           L
135436 2025-08-04 08:31:49.413733           L
135437 2025-08-04 08:31:49.413733           L
135439 2025-08-04 08:31:56.936551           L

[134134 rows x 13 columns]
2.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135434      135434  135435        1530     tu peux mieux écrire
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135434 2025-08-04 08:27:42.041                       0
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135434  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135434          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135439          96                               NaN

               message_created_at user_status          previous_content  \
0      2024-06-08 11:19:08.554499           L                      None
1      2024-06-08 11:19:08.554499           L                         H
2      2024-06-08 11:19:08.554499           L                        He
3      2024-06-08 11:19:08.554499           L                       Hel
4      2024-06-08 11:19:08.554499           L                      Hell
...                           ...         ...                       ...
135434 2025-08-04 08:31:49.413733           L      tu peux mieux écrire
135435 2025-08-04 08:31:49.413733           L     tu peux mieux écrire
135436 2025-08-04 08:31:49.413733           L    tu peux mieux écrire ç
135437 2025-08-04 08:31:49.413733           L   tu peux mieux écrire ça
135439 2025-08-04 08:31:56.936551           L  tu peux mieux écrire ça?

        previous_message_id
0                       NaN
1                       1.0
2                       1.0
3                       1.0
4                       1.0
...                     ...
135434               1530.0
135435               1530.0
135436               1530.0
135437               1530.0
135439               1530.0

[134134 rows x 15 columns]
3.         Unnamed: 0  key_id  message_id                   content  \
0                0       1           1                         H
1                1       2           1                        He
2                2       3           1                       Hel
3                3       4           1                      Hell
4                4       5           1                     Hello
...            ...     ...         ...                       ...
135434      135434  135435        1530     tu peux mieux écrire
135435      135435  135436        1530    tu peux mieux écrire ç
135436      135436  135437        1530   tu peux mieux écrire ça
135437      135437  135438        1530  tu peux mieux écrire ça?
135439      135439  135440        1531                         f

                      key_time  event_for_message_type  \
0      2024-06-08 09:19:07.999                       0
1      2024-06-08 09:19:08.122                       0
2      2024-06-08 09:19:08.232                       0
3      2024-06-08 09:19:08.377                       0
4      2024-06-08 09:19:08.522                       0
...                        ...                     ...
135434 2025-08-04 08:27:42.041                       0
135435 2025-08-04 08:27:42.168                       0
135436 2025-08-04 08:27:42.527                       0
135437 2025-08-04 08:27:42.748                       0
135439 2025-08-04 08:31:54.510                       0

                             message_uid           message_content  user_id  \
0       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
1       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
2       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
3       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
4       OrovKJP0X4nJgcs22N6cxfLSwYVFGbWu                     Hello        1
...                                  ...                       ...      ...
135434  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135435  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135436  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135437  YFWibY5E6tl7cHZ_EqdV8Ru7dDANTNJ8  tu peux mieux écrire ça?       10
135439  1RLCfOWw1g-9QRxqna_dnVjPIK4EZwFY                        fn       35

        session_id               reply_to_message_id  \
0                1                               NaN
1                1                               NaN
2                1                               NaN
3                1                               NaN
4                1                               NaN
...            ...                               ...
135434          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135435          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135436          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135437          96  gTdySRISEqv1sybfXd9d-ipr-ZonOWv8
135439          96                               NaN

               message_created_at user_status          previous_content  \
0      2024-06-08 11:19:08.554499           L                      None
1      2024-06-08 11:19:08.554499           L                         H
2      2024-06-08 11:19:08.554499           L                        He
3      2024-06-08 11:19:08.554499           L                       Hel
4      2024-06-08 11:19:08.554499           L                      Hell
...                           ...         ...                       ...
135434 2025-08-04 08:31:49.413733           L      tu peux mieux écrire
135435 2025-08-04 08:31:49.413733           L     tu peux mieux écrire
135436 2025-08-04 08:31:49.413733           L    tu peux mieux écrire ç
135437 2025-08-04 08:31:49.413733           L   tu peux mieux écrire ça
135439 2025-08-04 08:31:56.936551           L  tu peux mieux écrire ça?

        previous_message_id    action
0                       NaN      None
1                       1.0  addition
2                       1.0  addition
3                       1.0  addition
4                       1.0  addition
...                     ...       ...
135434               1530.0  addition
135435               1530.0  addition
135436               1530.0  addition
135437               1530.0  addition
135439               1530.0      None

[134134 rows x 16 columns]
Index(['Unnamed: 0', 'key_id', 'message_id', 'content', 'key_time',
       'event_for_message_type', 'message_uid', 'message_content', 'user_id',
       'session_id', 'reply_to_message_id', 'message_created_at',
       'user_status', 'action'],
      dtype='object')
                        content    action
0                             H      None
1                            He  addition
2                           Hel  addition
3                          Hell  addition
4                         Hello  addition
5                             H      None
6                            He  addition
7                           Hel  addition
8                          Hell  addition
9                         Hello  addition
10                          NaN       NaN
11                            H      None
12                           Ho  addition
13                          How  addition
14                         How   addition
15                        How a  addition
16                       How ar  addition
17                      How are  addition
18                     How are   addition
19                    How are y  addition
20                   How are yo  addition
21                  How are you  addition
22                 How are you?  addition
23                            H      None
24                           Hi  addition
25                          Hi   addition
26                         Hi g  addition
27                        Hi gu  addition
28                       Hi guy  addition
29                      Hi guy!  addition
30                     Hi guy!   addition
31                    Hi guy! T  addition
32                   Hi guy! Te  addition
33                  Hi guy! Tel  addition
34                 Hi guy! Tell  addition
35                Hi guy! Tell   addition
36               Hi guy! Tell m  addition
37              Hi guy! Tell me  addition
38             Hi guy! Tell me   addition
39            Hi guy! Tell me w  addition
40           Hi guy! Tell me wh  addition
41          Hi guy! Tell me whe  addition
42         Hi guy! Tell me when  addition
43        Hi guy! Tell me when   addition
44       Hi guy! Tell me when y  addition
45      Hi guy! Tell me when yo  addition
46     Hi guy! Tell me when you  addition
47    Hi guy! Tell me when you'  addition
48   Hi guy! Tell me when you'r  addition
49  Hi guy! Tell me when you're  addition
                                                  content        action
132261                                                NaN           NaN
132262                                                  Y          None
132263                                                 Ye      addition
132264                                                Yes      addition
132265                                               Yes,      addition
132266                                              Yes,       addition
132267                                             Yes, "      addition
132268                                            Yes, "j      addition
132269                                           Yes, "je      addition
132270                                          Yes, "je       addition
132271                                         Yes, "je l      addition
132272                                        Yes, "je le      addition
132273                                       Yes, "je les      addition
132274                                      Yes, "je les       addition
132275                                     Yes, "je les p      addition
132276                                    Yes, "je les pe      addition
132277                                   Yes, "je les per      addition
132278                                  Yes, "je les perd      addition
132279                                 Yes, "je les perdu      addition
132280                                Yes, "je les perdue      addition
132281                               Yes, "je les perdues      addition
132282                                Yes"je les perdues"  substitution
132283                               Yes,"je les perdues"      addition

## add_span

In [ ]:
## add_span with too many colnames --> error
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_span(colnames=['content', "action", "start_deletion_span", "end_deletion_span", "start_addition_span", "end_addition_span"])
print(default_ll.columns)
print(default_ll[['content', "action", "start_deletion_span", "end_deletion_span", "start_addition_span", "end_addition_span"]].head(50))

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)

ValueError: colnames must be a list of 4 strings (or None).

In [1]:
## add_span correclty
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_span(colnames=["start_deletion_span", "end_deletion_span", "start_addition_span", "end_addition_span"])
print(default_ll.columns)
print(default_ll[['content', "start_deletion_span", "end_deletion_span", "start_addition_span", "end_addition_span"]].head(50))

addition
None
None
3
4
Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
Index(['Unnamed: 0', 'key_id', 'message_id', 'content', 'key_time',
       'event_for_message_type', 'message_uid', 'message_content', 'user_id',
       'session_id', 'reply_to_message_id', 'message_created_at',
       'user_status', 'start_deletion_span', 'end_deletion_span',
       'start_addition_span', 'end_addition_span'],
      dtype='object')
                        content  start_deletion_span  end_deletion_span  \
0                             H                  NaN                NaN
1                            He                  NaN                NaN
2                           Hel                  NaN                NaN
3                          Hell                  NaN                NaN
4                         Hello                  NaN                NaN
5                             H                  NaN                NaN
6                            He                  NaN                NaN
7                           Hel                  NaN                NaN
8                          Hell                  NaN                NaN
9                         Hello                  NaN                NaN
10                          NaN                  NaN                NaN
11                            H                  NaN                NaN
12                           Ho                  NaN                NaN
13                          How                  NaN                NaN
14                         How                   NaN                NaN
15                        How a                  NaN                NaN
16                       How ar                  NaN                NaN
17                      How are                  NaN                NaN
18                     How are                   NaN                NaN
19                    How are y                  NaN                NaN
20                   How are yo                  NaN                NaN
21                  How are you                  NaN                NaN
22                 How are you?                  NaN                NaN
23                            H                  NaN                NaN
24                           Hi                  NaN                NaN
25                          Hi                   NaN                NaN
26                         Hi g                  NaN                NaN
27                        Hi gu                  NaN                NaN
28                       Hi guy                  NaN                NaN
29                      Hi guy!                  NaN                NaN
30                     Hi guy!                   NaN                NaN
31                    Hi guy! T                  NaN                NaN
32                   Hi guy! Te                  NaN                NaN
33                  Hi guy! Tel                  NaN                NaN
34                 Hi guy! Tell                  NaN                NaN
35                Hi guy! Tell                   NaN                NaN
36               Hi guy! Tell m                  NaN                NaN
37              Hi guy! Tell me                  NaN                NaN
38             Hi guy! Tell me                   NaN                NaN
39            Hi guy! Tell me w                  NaN                NaN
40           Hi guy! Tell me wh                  NaN                NaN
41          Hi guy! Tell me whe                  NaN                NaN
42         Hi guy! Tell me when                  NaN                NaN
43        Hi guy! Tell me when                   NaN                NaN
44       Hi guy! Tell me when y                  NaN                NaN
45      Hi guy! Tell me when yo                  NaN                NaN
46     Hi guy! Tell me when you                  NaN                NaN
47    Hi guy! Tell me when you'                  NaN                NaN
48   Hi guy! Tell me when you'r                  NaN                NaN
49  Hi guy! Tell me when you're                  NaN                NaN

    start_addition_span  end_addition_span
0                   NaN                NaN
1                   1.0                2.0
2                   2.0                3.0
3                   3.0                3.0
4                   4.0                5.0
5                   NaN                NaN
6                   1.0                2.0
7                   2.0                3.0
8                   3.0                3.0
9                   4.0                5.0
10                  NaN                NaN
11                  NaN                NaN
12                  1.0                2.0
13                  2.0                3.0
14                  3.0                4.0
15                  4.0                5.0
16                  5.0                6.0
17                  6.0                7.0
18                  7.0                8.0
19                  8.0                9.0
20                  9.0               10.0
21                 10.0               11.0
22                 11.0               12.0
23                  NaN                NaN
24                  1.0                2.0
25                  2.0                3.0
26                  3.0                4.0
27                  4.0                5.0
28                  5.0                6.0
29                  6.0                7.0
30                  7.0                8.0
31                  8.0                9.0
32                  9.0               10.0
33                 10.0               11.0
34                 11.0               11.0
35                 12.0               13.0
36                 13.0               14.0
37                 14.0               15.0
38                 15.0               16.0
39                 16.0               17.0
40                 17.0               18.0
41                 18.0               19.0
42                 19.0               20.0
43                 20.0               21.0
44                 21.0               22.0
45                 22.0               23.0
46                 23.0               24.0
47                 24.0               25.0
48                 25.0               26.0
49                 26.0               27.0

In [2]:
# add selection of spans
import src.keylogging_analysis as ka
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_span(colnames=["start_deletion_span", None, None, None], selection=[True, False, False, False])
print(default_ll.columns)
print(default_ll[['content', "start_deletion_span"]].head(50))

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
Index(['Unnamed: 0', 'key_id', 'message_id', 'content', 'key_time',
       'event_for_message_type', 'message_uid', 'message_content', 'user_id',
       'session_id', 'reply_to_message_id', 'message_created_at',
       'user_status', 'start_deletion_span', 'end_deletion_span',
       'start_addition_span', 'end_addition_span'],
      dtype='object')
                        content  start_deletion_span
0                             H                  NaN
1                            He                  NaN
2                           Hel                  NaN
3                          Hell                  NaN
4                         Hello                  NaN
5                             H                  NaN
6                            He                  NaN
7                           Hel                  NaN
8                          Hell                  NaN
9                         Hello                  NaN
10                          NaN                  NaN
11                            H                  NaN
12                           Ho                  NaN
13                          How                  NaN
14                         How                   NaN
15                        How a                  NaN
16                       How ar                  NaN
17                      How are                  NaN
18                     How are                   NaN
19                    How are y                  NaN
20                   How are yo                  NaN
21                  How are you                  NaN
22                 How are you?                  NaN
23                            H                  NaN
24                           Hi                  NaN
25                          Hi                   NaN
26                         Hi g                  NaN
27                        Hi gu                  NaN
28                       Hi guy                  NaN
29                      Hi guy!                  NaN
30                     Hi guy!                   NaN
31                    Hi guy! T                  NaN
32                   Hi guy! Te                  NaN
33                  Hi guy! Tel                  NaN
34                 Hi guy! Tell                  NaN
35                Hi guy! Tell                   NaN
36               Hi guy! Tell m                  NaN
37              Hi guy! Tell me                  NaN
38             Hi guy! Tell me                   NaN
39            Hi guy! Tell me w                  NaN
40           Hi guy! Tell me wh                  NaN
41          Hi guy! Tell me whe                  NaN
42         Hi guy! Tell me when                  NaN
43        Hi guy! Tell me when                   NaN
44       Hi guy! Tell me when y                  NaN
45      Hi guy! Tell me when yo                  NaN
46     Hi guy! Tell me when you                  NaN
47    Hi guy! Tell me when you'                  NaN
48   Hi guy! Tell me when you'r                  NaN
49  Hi guy! Tell me when you're                  NaN

## add_length()

## test pause_analysis()

In [1]:
import src.keylogging_analysis as ka
import pandas as pd
from IPython.display import display

default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
default_ll.add_iki()
default_ll.add_pause(method="fixed", threshold=2000, colname="pause2000", iki_colname="iki")
pause_metrics = default_ll[default_ll["user_id"] == 1].pause_analysis(pause_colname="pause2000", iki_colname="iki")
display(pause_metrics)

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)

,nb_pauses,percentage_pauses_per_keys,total_pause_duration,percentage_pause_duration,avg_pause_length,std_pause_length,median_pause_length,mad_pause_length,max_pause_length,min_pause_length
0,3,0.708,6408,9.579,2136.0,112.468,2181,38,2219,2008

In [3]:
metrics_per_user = default_ll.groupby("user_id").apply(
    lambda g: g.pause_analysis(pause_colname="pause2000", iki_colname="iki"))
from IPython.display import display
display(metrics_per_user)

C:\Users\kobet\AppData\Local\Temp\ipykernel_17056\560550148.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  metrics_per_user = default_ll.groupby("user_id").apply(
C:\Users\kobet\AppData\Local\Temp\ipykernel_17056\560550148.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  metrics_per_user = default_ll.groupby("user_id").apply(

,,nb_pauses,percentage_pauses_per_keys,total_pause_duration,percentage_pause_duration,avg_pause_length,std_pause_length,median_pause_length,mad_pause_length,max_pause_length,min_pause_length
user_id,,,,,,,,,,,
1,0,3,0.708,6408,9.579,2136.000,112.468,2181,38,2219,2008
2,0,0,0.000,0,0.000,NaN,NaN,None,None,None,None
4,0,0,0.000,0,0.000,NaN,NaN,None,None,None,None
8,0,801,1.256,5824277,36.861,7271.257,13677.708,3723,1399,229283,2001
10,0,34,1.471,470027,52.293,13824.324,24369.177,4392,1564,88746,2159
12,0,2211,3.402,9905652,43.279,4480.168,4488.312,3312,969,93471,2001
13,0,2,3.704,4783,23.159,2391.500,409.415,2391,289,2681,2102
18,0,0,0.000,0,0.000,NaN,NaN,None,None,None,None
22,0,20,0.892,76613,20.385,3830.650,2294.250,3361,850,12041,2026
30,0,1,0.893,13523,35.622,13523.000,NaN,13523,0,13523,13523
33,0,2,9.524,10808,62.804,5404.000,3299.360,5404,2333,7737,3071
35,0,0,0.000,0,0.000,NaN,NaN,None,None,None,None

## burst analysis

In [1]:
# test burst dataframe
import src.keylogging_analysis as ka
import pandas as pd
pd.set_option('display.max_rows', 300)
default_ll = ka.KeyLoggingDataFrame()
default_ll.load_default_data("ll")
print(default_ll.columns)
default_ll.add_pburst(colname="pburst", pause_colname="pause", pause_method="fixed", pause_threshold=2000)
burst_df = default_ll.burst_dataframe(burst_colname="pburst")

Loaded 135440 events
KeyLoggingDataFrame of shape (135440, 13)
Index(['Unnamed: 0', 'key_id', 'message_id', 'content', 'key_time',
       'event_for_message_type', 'message_uid', 'message_content', 'user_id',
       'session_id', 'reply_to_message_id', 'message_created_at',
       'user_status'],
      dtype='object')

KeyError: 'pause'